baseURL = 'https://s0lowalker.github.io/'
languageCode = 'zh-cn'
title = 'Solowalker'
theme = 'hugo-book'

[params]
  BookTheme = 'auto'
  BookLogo = '/images/logo/solowalker.png'
  BookSection = 'docs'

# 导航链接
[[params.navLinks]]
  name = "GitHub"
  url = "https://github.com/s0lowalker"